# Default values for methode-image-model-mapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
eksCluster: false
replicaCount: 2
image:
  repository: coco/methode-image-model-mapper
  pullPolicy: Always
resources:
  requests:
    memory: 512Mi
  limits:
    memory: 1Gi


